# Generated by Django 4.2.2 on 2023-06-17 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MANIMath_Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
