# Generated by Django 4.2.2 on 2023-06-18 09:48

import MANIMath_Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MANIMath_Account', '0002_profile_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='/static/media/img/Default_Profile_Picture.png', null=True, upload_to=MANIMath_Account.models.get_profile_photo_path),
        ),
    ]
