# Generated by Django 4.2.2 on 2023-06-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MANIMath_WebUI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
