# Generated by Django 4.2.2 on 2023-06-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MANIMath_Data', '0004_searchmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rootfindingmodel',
            options={'verbose_name': 'Root Finding Algorithm Model', 'verbose_name_plural': 'Root Finding Algorithm Model'},
        ),
    ]
