# Generated by Django 4.2.2 on 2023-07-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MANIMath_Data', '0005_alter_rootfindingmodel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functionmodel',
            old_name='equation1',
            new_name='equation',
        ),
        migrations.RenameField(
            model_name='functionmodel',
            old_name='equation2',
            new_name='equation_2',
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='axes_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='domain',
            field=models.CharField(blank=True, default='-10,10,1', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='dot_color',
            field=models.CharField(blank=True, default='#FFFF00', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='equation_color',
            field=models.CharField(blank=True, default='#0000FF', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='include_numbers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='include_tip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='input_array',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='iteration',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='line_color',
            field=models.CharField(blank=True, default='#FF0000', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='point_1',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='point_2',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='scale',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='text_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='x_length',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='x_range',
            field=models.CharField(blank=True, default='-10,10,1', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='y_length',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
        migrations.AddField(
            model_name='functionmodel',
            name='y_range',
            field=models.CharField(blank=True, default='-10,10,1', max_length=16, null=True),
        ),
    ]
