# Generated by Django 4.2.2 on 2023-07-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MANIMath_Data', '0006_rename_equation1_functionmodel_equation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionmodel',
            name='axes_color',
            field=models.CharField(blank=True, default='#000000', max_length=32, null=True),
        ),
    ]
