# Generated by Django 4.2.2 on 2023-07-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MANIMath_Data', '0007_alter_functionmodel_axes_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionmodel',
            name='iteration',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='functionmodel',
            name='point_1',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='functionmodel',
            name='point_2',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
    ]
