# Generated by Django 4.2.2 on 2023-07-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MANIMath_Data', '0012_rename_equation1_rootfindingmodel_equation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchmodel',
            name='line_color',
            field=models.CharField(blank=True, default='#FF0000', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='scale',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='shape_color',
            field=models.CharField(blank=True, default='#FFFF00', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='text_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='sortmodel',
            name='line_color',
            field=models.CharField(blank=True, default='#FF0000', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='sortmodel',
            name='scale',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='sortmodel',
            name='shape_color',
            field=models.CharField(blank=True, default='#FFFF00', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='sortmodel',
            name='target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sortmodel',
            name='text_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='functionmodel',
            name='domain',
            field=models.CharField(blank=True, default='-5,5,1', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='functionmodel',
            name='x_range',
            field=models.CharField(blank=True, default='-5,5,1', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='functionmodel',
            name='y_range',
            field=models.CharField(blank=True, default='-5,5,1', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='rootfindingmodel',
            name='domain',
            field=models.CharField(blank=True, default='-5,5,1', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='rootfindingmodel',
            name='x_range',
            field=models.CharField(blank=True, default='-5,5,1', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='rootfindingmodel',
            name='y_range',
            field=models.CharField(blank=True, default='-5,5,1', max_length=16, null=True),
        ),
    ]
